# Generated by Django 3.1 on 2020-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='pic',
            field=models.ImageField(upload_to='pic/'),
        ),
    ]
