# Generated by Django 3.1 on 2020-09-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200909_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='descrip',
            new_name='descrip1',
        ),
        migrations.AddField(
            model_name='blogs',
            name='descrip2',
            field=models.TextField(null=True),
        ),
    ]
