# Generated by Django 3.1 on 2020-09-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200910_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='descrip1',
            new_name='descrip',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='descrip2',
        ),
    ]
